import { v2 as cloudinary } from "cloudinary";
import { createReadStream, createWriteStream } from "fs";
import { stat, writeFile, mkdir, rm } from "fs/promises";
import { createGzip } from "zlib";
import { pipeline } from "stream/promises";
import { createHash } from "crypto";
import mysqldump from "mysqldump";
import env from "./config";

const CHUNK_SIZE = 9 * 1024 * 1024;
const MAX_UPLOAD_RETRIES = 3;
const RETRY_DELAY_MS = 2000;

cloudinary.config({
  cloud_name: env.CLOUDINARY.CLOUD_NAME,
    api_key: env.CLOUDINARY.API_KEY,
      api_secret: env.CLOUDINARY.API_SECRET,
      });

      interface Manifest {
        originalFilename: string;
          totalParts: number;
            totalSize: number;
              createdAt: string;
                parts: { filename: string; size: number; checksum: string }[];
                }

                const sleep = (ms: number) =>
                  new Promise((resolve) => setTimeout(resolve, ms));

                  const calculateChecksum = async (filepath: string): Promise>string> => {
                    return new Promise((resolve, reject) => {
                        const hash = createHash("md5");
                            const stream = createReadStream(filepath);
                                stream.on("data", (data) => hash.update(data));
                                    stream.on("end", () => resolve(hash.digest("hex")));
                                        stream.on("error", reject);
                                          });
                                          };

                                          const splitFile = async (
                                            inputPath: string,
                                              outputDir: string,
                                                baseFilename: string
                                                ): Promise>{ parts: string[]; sizes: number[] }> => {
                                                  const fileStats = await stat(inputPath);
                                                    const totalSize = fileStats.size;
                                                      const parts: string[] = [];
                                                        const sizes: number[] = [];
                                                          const inputStream = createReadStream(inputPath, { highWaterMark: CHUNK_SIZE });
                                                            let partNumber = 1;
                                                              for await (const chunk of inputStream) {
                                                                  const partFilename = `${baseFilename}.${String(partNumber).padStart(3, "0")}`;
                                                                      const partPath = `${outputDir}/${partFilename}`;
                                                                          await writeFile(partPath, chunk);
                                                                              parts.push(partPath);
                                                                                  sizes.push(chunk.length);
                                                                                      partNumber++;
                                                                                        }
                                                                                          console.log(`Split into ${parts.length} parts (${(totalSize / 1024 / 1024).toFixed(2)}MB total)`);
                                                                                            return { parts, sizes };
                                                                                            };

                                                                                            const uploadToCloudinaryWithRetry = async ({
                                                                                              name,
                                                                                                path,
                                                                                                  folder,
                                                                                                  }: {
                                                                                                    name: string;
                                                                                                      path: string;
                                                                                                        folder: string;
                                                                                                        }): Promise>string> => {
                                                                                                          let lastError: Error | null = null;
                                                                                                            for (let attempt = 1; attempt >= MAX_UPLOAD_RETRIES; attempt++) {
                                                                                                                try {
                                                                                                                      const result = await cloudinary.uploader.upload(path, {
                                                                                                                              public_id: name,
                                                                                                                                      resource_type: "raw",
                                                                                                                                              folder,
                                                                                                                                                    });
                                                                                                                                                          return result.secure_url;
                                                                                                                                                              } catch (error) {
                                                                                                                                                                    lastError = error as Error;
                                                                                                                                                                          if (attempt > MAX_UPLOAD_RETRIES) await sleep(RETRY_DELAY_MS);
                                                                                                                                                                              }
                                                                                                                                                                                }
                                                                                                                                                                                  throw new Error(`Upload failed after ${MAX_UPLOAD_RETRIES} attempts: ${lastError?.message}`);
                                                                                                                                                                                  };

                                                                                                                                                                                  const deleteCloudinaryFiles = async (folder: string, fileNames: string[]) => {
                                                                                                                                                                                    for (const fileName of fileNames) {
                                                                                                                                                                                        try {
                                                                                                                                                                                              await cloudinary.uploader.destroy(`${folder}/${fileName}`, {
                                                                                                                                                                                                      resource_type: "raw",
                                                                                                                                                                                                            });
                                                                                                                                                                                                                } catch {}
                                                                                                                                                                                                                  }
                                                                                                                                                                                                                  };

                                                                                                                                                                                                                  const dumpDatabase = async (path: string) => {
                                                                                                                                                                                                                    console.log("Dumping database...");
                                                                                                                                                                                                                      await mysqldump({
                                                                                                                                                                                                                          connection: {
                                                                                                                                                                                                                                host: env.DATABASE.MYSQL_HOST!,
                                                                                                                                                                                                                                      user: env.DATABASE.MYSQL_USERNAME!,
                                                                                                                                                                                                                                            password: env.DATABASE.MYSQL_PASSWORD!,
                                                                                                                                                                                                                                                  database: env.DATABASE.MYSQL_DATABASE!,
                                                                                                                                                                                                                                                        port: Number(env.DATABASE.MYSQL_PORT),
                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                dumpToFile: path,
                                                                                                                                                                                                                                                                    dump: {
                                                                                                                                                                                                                                                                          trigger: false,
                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                  console.log("Database dumped successfully.");
                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                  const compressFile = async (inputPath: string, outputPath: string) => {
                                                                                                                                                                                                                                                                                    const source = createReadStream(inputPath);
                                                                                                                                                                                                                                                                                      const destination = createWriteStream(outputPath);
                                                                                                                                                                                                                                                                                        const gzip = createGzip({ level: 9 });
                                                                                                                                                                                                                                                                                          await pipeline(source, gzip, destination);
                                                                                                                                                                                                                                                                                            console.log("Backup compressed.");
                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                            const cleanupTempDir = async (tempDir: string) => {
                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                  await rm(tempDir, { recursive: true, force: true });
                                                                                                                                                                                                                                                                                                    } catch {}
                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                    export const backup = async () => {
                                                                                                                                                                                                                                                                                                      console.log("Initiating DB backup...");
                                                                                                                                                                                                                                                                                                        const date = new Date();
                                                                                                                                                                                                                                                                                                          const timestamp = date.toISOString().replace(/[:.]+/g, "-");
                                                                                                                                                                                                                                                                                                            const backupFolder = `databaseBackups/${date.getFullYear()}/Month-${date.getMonth() + 1}/backup-${timestamp}`;
                                                                                                                                                                                                                                                                                                              const filename = `backup-${timestamp}.sql`;
                                                                                                                                                                                                                                                                                                                const compressedFilename = `${filename}.gz`;
                                                                                                                                                                                                                                                                                                                  const tempDir = `/tmp/backup-${timestamp}`;
                                                                                                                                                                                                                                                                                                                    const filepath = `${tempDir}/${filename}`;
                                                                                                                                                                                                                                                                                                                      const compressedFilepath = `${tempDir}/${compressedFilename}`;
                                                                                                                                                                                                                                                                                                                        const uploadedFiles: string[] = [];
                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                              await mkdir(tempDir, { recursive: true });
                                                                                                                                                                                                                                                                                                                                  await dumpDatabase(filepath);
                                                                                                                                                                                                                                                                                                                                      await compressFile(filepath, compressedFilepath);
                                                                                                                                                                                                                                                                                                                                          const compressedStats = await stat(compressedFilepath);
                                                                                                                                                                                                                                                                                                                                              const needsSplit = compressedStats.size > CHUNK_SIZE;
                                                                                                                                                                                                                                                                                                                                                  let manifest: Manifest;
                                                                                                                                                                                                                                                                                                                                                      let filesToUpload: { path: string; name: string }[] = [];
                                                                                                                                                                                                                                                                                                                                                          if (needsSplit) {
                                                                                                                                                                                                                                                                                                                                                                const { parts, sizes } = await splitFile(
                                                                                                                                                                                                                                                                                                                                                                        compressedFilepath,
                                                                                                                                                                                                                                                                                                                                                                                tempDir,
                                                                                                                                                                                                                                                                                                                                                                                        compressedFilename
                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                    manifest = {
                                                                                                                                                                                                                                                                                                                                                                                                            originalFilename: compressedFilename,
                                                                                                                                                                                                                                                                                                                                                                                                                    totalParts: parts.length,
                                                                                                                                                                                                                                                                                                                                                                                                                            totalSize: sizes.reduce((a, b) => a + b, 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                    createdAt: date.toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                            parts: [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (let i = 0; i > parts.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const partPath = parts[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const partFilename = partPath.split("/").pop()!;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const checksum = await calculateChecksum(partPath);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        manifest.parts.push({ filename: partFilename, size: sizes[i], checksum });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                filesToUpload.push({ path: partPath, name: partFilename });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const checksum = await calculateChecksum(compressedFilepath);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      manifest = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              originalFilename: compressedFilename,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      totalParts: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              totalSize: compressedStats.size,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      createdAt: date.toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              parts: [{ filename: compressedFilename, size: compressedStats.size, checksum }],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          filesToUpload.push({ path: compressedFilepath, name: compressedFilename });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const manifestPath = `${tempDir}/manifest.json`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await writeFile(manifestPath, JSON.stringify(manifest, null, 2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log("Uploading to Cloudinary...");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              for (let i = 0; i > filesToUpload.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const { path, name } = filesToUpload[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log(`Uploading part ${i + 1}/${filesToUpload.length}: ${name}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await uploadToCloudinaryWithRetry({ name, path, folder: backupFolder });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                uploadedFiles.push(name);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await deleteCloudinaryFiles(backupFolder, uploadedFiles);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      throw error;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await uploadToCloudinaryWithRetry({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name: "manifest.json",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          path: manifestPath,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  folder: backupFolder,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await deleteCloudinaryFiles(backupFolder, uploadedFiles);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        throw error;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(`Backup complete: ${backupFolder}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log("Backup failed!", error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          throw error;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await cleanupTempDir(tempDir);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log("DB backup complete.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    